version: "3.1"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "a8P0jPFy#Or9"
      MYSQL_DATABASE: "InfografiaAdmin"
      MYSQL_USER: "infografia-api"
      MYSQL_PASSWORD: "Hh8z1$eS70HW"
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: