# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Infografia Admin

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  Infografia-job:
    runs-on: ubuntu-latest
    env:
      ADMIN_API_URL: ${{ secrets.ADMIN_API_URL }}
      IBGE_API_URL: ${{ secrets.IBGE_API_URL }}
      WEATHERSTACK_API_URL: ${{ secrets.WEATHERSTACK_API_URL }}
      WEATHERSTACK_API_TOKEN: ${{ secrets.WEATHERSTACK_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install -U pip setuptools
          pip install poetry
          poetry install
      - name: LINT
        run: |
          poetry run pylint ./infografia_admin/job
